/**
 * TP 02 POO - Sistema de Votações
 * Aluno: Samuel Jhonata S. Tavares - 2282
 * Prof.: Fabrício Aguiar Silva
 * UFV - Florestal - 2016
**/

package visao;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import controle.*;
import java.awt.Color;
import modelo.*;

public class Principal extends javax.swing.JFrame {

    ControlaUrna cUrna = new ControlaUrna();

    /**
     * Creates new form Principal
     */
    public Principal() { //construtor
        initComponents();
        if (!cUrna.carregaDados("candidatos.txt", "eleitores.txt")) { //le os arquivos
            ErroCarregarDados erro = new ErroCarregarDados(this, true);
            erro.setVisible(true);
        }
        btnIniciaEleicoes.setEnabled(false);
        BtnMesario.setEnabled(false);
        btnEncerraEleicoes.setEnabled(false);
        btnIniciaUrnas.setEnabled(false);
        btnIniciaUrnas.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIniciaUrnas = new javax.swing.JButton();
        btnIniciaEleicoes = new javax.swing.JButton();
        BtnMesario = new javax.swing.JButton();
        btnEncerraEleicoes = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Bem Vindo ao Sistema de Votação!");

        btnIniciaUrnas.setBackground(java.awt.Color.green);
        btnIniciaUrnas.setText("Iniciar Urnas");
        btnIniciaUrnas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciaUrnas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaUrnasActionPerformed(evt);
            }
        });

        btnIniciaEleicoes.setBackground(java.awt.Color.green);
        btnIniciaEleicoes.setText("Iniciar Eleição");
        btnIniciaEleicoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciaEleicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaEleicoesActionPerformed(evt);
            }
        });

        BtnMesario.setBackground(java.awt.Color.green);
        BtnMesario.setText("Mesário");
        BtnMesario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnMesario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMesarioActionPerformed(evt);
            }
        });

        btnEncerraEleicoes.setBackground(java.awt.Color.orange);
        btnEncerraEleicoes.setText("Encerra Eleição");
        btnEncerraEleicoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncerraEleicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerraEleicoesActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(java.awt.Color.red);
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setText("SAIR");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(100, 100, 100))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIniciaEleicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnMesario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEncerraEleicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIniciaUrnas, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(btnIniciaUrnas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciaEleicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnMesario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEncerraEleicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMesarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMesarioActionPerformed
        // TODO add your handling code here:
        Mesario mesario = new Mesario();
        mesario.setVisible(true);
    }//GEN-LAST:event_BtnMesarioActionPerformed

    private void btnIniciaEleicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaEleicoesActionPerformed
        // TODO add your handling code here:
        if (cUrna.liberaEleicoes()) {
            BtnMesario.setEnabled(true);
            btnEncerraEleicoes.setEnabled(true);
            btnIniciaUrnas.setEnabled(false);
            btnIniciaEleicoes.setEnabled(false);
        } else {
            BtnMesario.setEnabled(false);
            btnIniciaEleicoes.setEnabled(false);
        }

    }//GEN-LAST:event_btnIniciaEleicoesActionPerformed

    private void btnEncerraEleicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerraEleicoesActionPerformed
        UrnaEletronica urna = new UrnaEletronica(21);
        // TODO add your handling code here:
        cUrna.encerraVotacao(urna);
        BtnMesario.setEnabled(false);
        btnEncerraEleicoes.setEnabled(false);
    }//GEN-LAST:event_btnEncerraEleicoesActionPerformed

    private void btnIniciaUrnasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaUrnasActionPerformed
        // TODO add your handling code here:
        IniciaUrnas janela = new IniciaUrnas();
        janela.setVisible(true);
    }//GEN-LAST:event_btnIniciaUrnasActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        /*libera botão para iniciar as eleições*/
        if (cUrna.qtdUrnas() > 0 && !cUrna.isVotacaoLiberada()) {
            btnIniciaEleicoes.setEnabled(true);
            btnIniciaUrnas.setBackground(Color.orange);

        } else {
            btnIniciaEleicoes.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowActivated

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        System.exit(0); //termina a execução
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnMesario;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEncerraEleicoes;
    private javax.swing.JButton btnIniciaEleicoes;
    private javax.swing.JButton btnIniciaUrnas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
